Guides in the documentation
liteflow-labs/liteflow-js pull request #201
Opened 2023-12-11 05:28 UTC by antho1404

This PR adds guides to the documentation in the `/guides` section.
For now the following guides are covered
- Setting up platform fees
- Setting up currencies
- Importing a collection
- Setting up a drop
- Understanding ABI

Things that could be added in other PRs
- Video going over the different steps
- Screenshots for each part

2023-12-11 06:05 UTC, EmmanuelDrouin requested changes
**Overall question**
- Should we include the page for the ABI and the drops setting inside a "drops" group? Currently set as 2 different pages, I feel like UX wise those should be grouped

2023-12-12 03:08 UTC, antho1404 reviewed
@EmmanuelDrouin I moved all your comments on dedicated files so it will be easier to track

2023-12-12 03:08 UTC, antho1404 commented on docs/pages/guides/setup-fees.mdx
Comment from @EmmanuelDrouin 

- Add a part to make it clear that those plugins cannot be cumulated, a user has to choose one or the other
  - Currently missing and could be understood as cumulative plugins instead of "radio" plugin (cf feedback from Johann)
- Add a warning about changing fee structure while being live (make sure the readers understand the impact of this change)
  - We have a small one at the top but this is not driving the idea of the impact while being live (what will happen, should I do it, will I break my platform, etc.)
- Add links to the dashboard and relevant pages for users to start setting up their fee
  - Like you did on the Product pages and other guides
- Overall feedback, this page does not follow the flow/layout of other guides with "Steps to ...", should we tweak this to fit the flow of the other pages? Currently I'm good with the content

2023-12-12 03:08 UTC, antho1404 commented on docs/pages/guides/setup-currencies.mdx
Comment from @EmmanuelDrouin 

- Change page title for "Setting Up Currencies" for consistency across pages
- Remove at the end of 1st paragraph "Here's a step-by-step guide based on your screenshot."

2023-12-12 03:08 UTC, antho1404 commented on docs/pages/guides/import-collection.mdx
Comment from @EmmanuelDrouin 

- Change 2nd title from "Steps for Importing a Collection" to "Steps to Import a Collection" for consistency across pages
- Steps > remove ":" at the end of each title (eg: Access Collections)

2023-12-12 03:08 UTC, antho1404 commented on docs/pages/guides/drop.mdx
Comment from @EmmanuelDrouin 

- Change page title for "Setting Up a Drop" for consistency across pages
- Change "Creating a Drop" to "Steps to Create a Drop" for consistency across pages
- Smart Contract Requirements page > In the warning box, remove spacing between sentences to make the alert more "compact"

2023-12-12 03:08 UTC, antho1404 commented on docs/pages/guides/abi.mdx
Comment from @EmmanuelDrouin 

- Add links to Drops guide
- We could add the links to the different explorers for ETH, Binance, Polygon and Lightlink so users do not have to search (especially with new chains added, or for new users in the space)

2023-12-12 04:01 UTC, antho1404 commented on docs/pages/guides/setup-fees.mdx
Done here [5d60798](https://github.com/liteflow-labs/liteflow-js/pull/201/commits/5d607984b01a06b261f4f03d321080d091c47d34)

2023-12-12 04:01 UTC, antho1404 commented on docs/pages/guides/setup-currencies.mdx
Done here [0d58d80](https://github.com/liteflow-labs/liteflow-js/pull/201/commits/0d58d80449ec32fe48818a4caec176740a7d6df4)

2023-12-12 04:01 UTC, antho1404 commented on docs/pages/guides/import-collection.mdx
Done here [26d88c0](https://github.com/liteflow-labs/liteflow-js/pull/201/commits/26d88c0aae21c0b11e6085271884d8d2375f9389)

2023-12-12 04:02 UTC, antho1404 commented on docs/pages/guides/drop.mdx
Done here [efa7905](https://github.com/liteflow-labs/liteflow-js/pull/201/commits/efa7905fe7bc5bb3d9876d564a448857206f5281)

2023-12-12 04:02 UTC, antho1404 commented on docs/pages/guides/abi.mdx
Done here [c0a373e](https://github.com/liteflow-labs/liteflow-js/pull/201/commits/c0a373ebb33a67e7054c7b95856e1166538769c1)

2023-12-12 04:07 UTC, antho1404 commented
> Should we include the page for the ABI and the drops setting inside a "drops" group? Currently set as 2 different pages, I feel like UX wise those should be grouped

The weird UX issue is that the ABI guide ends on the drop. 
I would suggest simply removing the "Connecting ABI to Liteflow's Drop System" in the ABI guide. This way, we don't have this connection back to Drop that feels like we need to go from Drop to Abi and back to Drop. This ABI page should be standalone, and putting it in the drop guide might be overwhelming for just one field that is often auto-detected and, if not, guided from the drop form.

2023-12-13 04:32 UTC, EmmanuelDrouin commented on docs/pages/guides/setup-fees.mdx
Perfect let's go

2023-12-13 04:32 UTC, EmmanuelDrouin commented on docs/pages/guides/setup-currencies.mdx
Perfect let's go

2023-12-13 04:33 UTC, EmmanuelDrouin commented on docs/pages/guides/import-collection.mdx
Perfect let's go

2023-12-13 04:33 UTC, EmmanuelDrouin commented on docs/pages/guides/drop.mdx
Perfect let's go

2023-12-13 04:34 UTC, EmmanuelDrouin commented on docs/pages/guides/abi.mdx
Perfect let's go

2023-12-13 04:34 UTC, EmmanuelDrouin commented
@antho1404 all good for me to merge  the current version 🥳

2023-12-13 06:43 UTC, EmmanuelDrouin approved these changes

2023-12-13 06:50 UTC, merged